### ISSUE TITLE
求 viewData 模块，injectObject 模块 的实例

### ISSUE THREAD

**Issue by visamz** [typecho/framework-example#1]
70 大大 能否 抽空 补充一下几个使用实例呢：  

1、`framework / Mvc / Data / AbstractData.php` 这个跌代器中元素是三维数组，突然不知道该如何应用了，旧版本的 typecho 里的数据跌代器是二维数组，这个该如何使用？求实例 ~~

2、`framework / Mvc / Base.php` 这个注入模块，目前为止我只知道可以把 new Server 扔进去，不知道还有什么其它使用场景，求实例~~

3、Action 里 如何实现把 变量 自动反射给 模板用？实例当中是把类成员变量 反射给模板用，如果变量较多，不可能一个个写成员变量，这样挺让人纠结的~~

4、如何算定义 error 和 notFound 这两个进入 action 来指定 模板文件 ？因为有需要把数据变量 反射给相应 模板使用 这样一个场景~~

70 大大，求实例啊 求实例~~

**Comment by joyqi** [comment]
got，实例马上到来

**Comment by visamz** [comment]
说好的实例呢 - -!

**Comment by joyqi** [comment]
@byends 这两天在忙于其它事，耽误了一下，已经补上

**Comment by joyqi** [comment]
自定义notFound和error，稍后送上

**Comment by visamz** [comment]
求 自定义notFound和error ~~~~
